### ISSUE TITLE
Display Current APR on the stats page

### ISSUE THREAD

**Issue by JustinCast** [EveripediaNetwork/iq-bridge-ui#109]

**Comment by kesar** [comment]
probably APR makes more sense since we don't compound rewards.

If I am not wrong, APR can be ( approximately ) calculated by:

(your_hiiq / total_hiiq) * 365M IQ  

example:

1 M HI IQ / 100 M HI IQ * 365M IQ = 3.65M IQ which is a 365% APR

5 M HI IQ / 10 M HI IQ * 365M IQ = 182.5M which is a 18250% APR

**Comment by kesar** [comment]
screens from some metrics curve shows:

I think we should show next distribution window time as well

![Captura de pantalla 2021-08-04 123655](https://user-images.githubusercontent.com/1288106/129040382-e4231e6f-6817-492a-b53e-22721c155e81.png)

![Captura de pantalla 2021-08-04 123647](https://user-images.githubusercontent.com/1288106/129040385-47b0cfa2-2189-4d41-a582-696fe7f80605.png)
